
name: print-event

on:
  workflow_dispatch
#  discussion:
#  discussion_comment:
#  issues:
#  issue_comment:
#  pull_request:
#  pull_request_review:
#  pull_request_review_comment:
# workflow_run
# pull_request_target


jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT